version: '3'
services:
  booknet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booknet
    restart: unless-stopped
    working_dir: /var/www/booknet
    environment:
      DB_CONNECTION: mysql
      DB_HOST: booknet_db
      DB_PORT: 3306
      DB_DATABASE: booknet
      DB_USERNAME: root
      DB_PASSWORD: 12345
    volumes:
      - ./src:/var/www/booknet
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/booknet
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  booknet_db:
    image: mysql:5.7.22
    container_name: booknet_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: booknet
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
